services:
  - type: web
    name: jobcat-app  # You can change this to match your Render web service name
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn jobcat_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: jobcat_project.settings
      - key: DATABASE_URL
        fromDatabase:
          name: jobcat-db  # 👈 Change this if your DB name on Render is different
          property: connectionString

    postDeployCommand: |
      python manage.py migrate
